# Generated by Django 4.2.5 on 2024-12-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(default='example@email.com', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('identificacion', models.CharField(blank=True, max_length=45, null=True)),
                ('calificacion', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_intereses', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plazo', models.IntegerField()),
                ('fecha_solicitud', models.DateTimeField(default='2000-01-01 00:00:00')),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('cliente', models.ForeignKey(db_column='cliente_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='prestamos.clientes')),
            ],
            options={
                'db_table': 'prestamos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recibos_Prestamos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_recibo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('prestamo', models.ForeignKey(db_column='prestamo_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='prestamos.prestamos')),
            ],
            options={
                'db_table': 'recibos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='clientes',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='prestamos.usuarios'),
        ),
    ]
