# Generated by Django 4.2.5 on 2024-12-17 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibos_prestamos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('tipo_recibo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('prestamos', models.ForeignKey(db_column='prestamos_id', on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='prestamos.prestamos')),
            ],
            options={
                'db_table': 'recibos',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Recibos',
        ),
    ]
