# Generated by Django 4.2.5 on 2024-12-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='fecha_solicitud',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
