# Generated by Django 4.2.5 on 2024-12-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_recibos_prestamos_delete_recibos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='prestamos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': True},
        ),
    ]
