# Generated by Django 4.2.5 on 2024-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_alter_clientes_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(default='Nombre Apellido', max_length=100),
        ),
    ]
