# Generated by Django 4.2.5 on 2024-12-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_alter_clientes_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nombre_empresa',
            field=models.CharField(default='Nombre de la empresa', max_length=100),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nombre_usuario',
            field=models.CharField(default='Nombre de usuario', max_length=100),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(default='+54 11 1234-5678', max_length=25),
        ),
    ]
