# Generated by Django 4.2.5 on 2024-12-17 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_remove_prestamos_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='usuarios',
            field=models.ForeignKey(db_column='usuarios_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='prestamos.usuarios'),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='clientes',
            field=models.ForeignKey(db_column='clientes_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='prestamos.clientes'),
        ),
        migrations.AlterField(
            model_name='recibos_prestamos',
            name='prestamos',
            field=models.ForeignKey(db_column='prestamos_id', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='prestamos.prestamos'),
        ),
    ]
