# Generated by Django 4.2.5 on 2025-01-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_remove_usuarios_nombre_usuarios_nombre_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
