# Generated by Django 4.2.5 on 2025-02-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0006_clientes_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.CharField(default='example@email.com', max_length=100, unique=True),
        ),
    ]
