# Generated by Django 4.2.5 on 2025-02-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0008_alter_clientes_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='empleo_actual',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='imagen_dnifrente',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='imagen_dnireverso',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='imagen_recibo',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='ingresos_mensuales',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='terminos_y_condiciones',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recibos_prestamos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='recibos_prestamos',
            name='nombre_archivo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
