# Generated by Django 4.2.5 on 2025-02-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0009_prestamos_empleo_actual_prestamos_imagen_dnifrente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='fecha_de_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
