# Generated by Django 4.2.5 on 2025-02-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0011_alter_prestamos_tasa_intereses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
