# Generated by Django 4.2.5 on 2025-03-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0012_alter_prestamos_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
