# Generated by Django 4.2.5 on 2025-03-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0013_alter_prestamos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
